accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("profile/", SignUpView.as_view(), name="profile"),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

from django.contrib.auth import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('issues/', include('issues.urls')),
    path('', include('pages.urls')),
    path('accounts/', include("django.contrib.auth.urls")),
    path('accounts/', include('accounts.urls')),
]

issues/urls.py
from django.urls import path
from issues import views

urlpatterns = [
    path("", views.IssueListView.as_view(), name="list"),

    path("new/", views.IssueCreateView.as_view(), name="new"),
    path("<int:pk>", views.IssueDetailView.as_view(), name="detail"),
    path("<int:pk>/edit/", views.IssueUpdateView.as_view(), name="edit"),
    path("<int:pk>/delet/", views.IssueDeleteView.as_view(), name="delete"),
]

pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Team(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=256)

    def __str__(self):
        return self.name
    
class Role(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=256)

    def __str__(self):
        return self.name

class CustomUser(AbstractUser):
    team = models.ForeignKey(
        Team,
        on_delete=models.CASCADE,
        null=True, blank=True
    )
    role = models.ForeignKey(
        Role,
        on_delete=models.CASCADE,
        null=True, blank=True
    )
    is_product_owner = models.BooleanField(default=False)
    is_scrum_master = models.BooleanField(default=False)

issues/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse


# Create your models here.

class Status(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=256)
    
    def __str__(self):
        return self.name

class Issue(models.Model):
    summary = models.CharField(max_length=128)
    description = models.TextField()
    reporter = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name="assignee"
    )
    status = models.ForeignKey(
        Status,
        on_delete=models.CASCADE
    )
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.summary
    
    def get_absolute_url(self):
        return reverse("detail", args=[self.id])
    

pages/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ("email", "team", "role")


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm):
        model = CustomUser
        fields = UserChangeForm.Meta.fields

accounts/views.py
from django.views.generic import CreateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy


# Create your views here.


class SignUpView(CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")

issues/views.py
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)

from .models import Issue, Status
from accounts.models import Role
from django.urls import reverse_lazy
from django.contrib.auth.mixins import (
    LoginRequiredMixin, UserPassesTestMixin)
from django.core.exceptions import PermissionDenied
from accounts.forms import CustomUser
from django.shortcuts import render, redirect

class IssueListView(ListView):
    template_name = "issues/list.html"
    model = Issue

class IssueDetailView(DetailView):
    template_name = "issues/detail.html"
    model = Issue

class IssueCreateView(UserPassesTestMixin, CreateView):
    template_name = "issues/new.html"
    model = Issue
    fields = ["summary", "description", "assignee", "status"]
    success_url = reverse_lazy('list')  # Set the URL to redirect to upon successful form submission

    def test_func(self):
        # Implement the condition here
        return self.request.user.is_authenticated

    def form_valid(self, form):
        form.instance.reporter = self.request.user  # Set the reporter field
        return super().form_valid(form)


class IssueUpdateView(UserPassesTestMixin, UpdateView):
    template_name = "issues/edit.html"
    model = Issue
    fields = ["summary", "description", "assignee", "status"]
    success_url = reverse_lazy("detail")

    def test_func(self):
        post = self.get_object()
        return self.request.user.is_product_owner

class IssueDeleteView(UserPassesTestMixin, DeleteView):
    template_name = "issues/delete.html"
    model = Issue
    success_url = reverse_lazy("list")

    def test_func(self):
        post = self.get_object()
        return self.request.user.is_scrum_master

pages/views.py
from django.views.generic import TemplateView

class HomePageView(TemplateView):
    template_name = "pages/home.html"

class AboutPageView(TemplateView):
    template_name = "pages/about.html"
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{%url 'home' %}">Menu</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{%url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'about' %}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'list' %}">Issues</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'new' %}">New Issue</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'password_change' %}">Change Password</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'logout' %}">Log Out</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'password_reset' %}">Reset Password</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'signup' %}">Sign Up</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
    {% block content %}

    {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>

</html>

templates/issues/delete.html
{% extends 'base.html' %}

{% block title %}Delete Post{% endblock title %}

{% block content %}
<h1>Delete Post</h1>
<p>Are you sure you want to delete "{{ post.title }}"?</p>
<form method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Confirm">
</form>
{% endblock content %}

templates/issues/detail.html
{% extends 'base.html' %}

{% block title %}{{ issue.title }}{% endblock title %}

{% block content %}


<h1>Details</h1>
<div class="container">


<div class="card">
    <div class="card-body">
        <h4 class="card-title">{{ issue.summary }}</h4>
        <h5 class="card-subtitle mb-2 text-body-secondary">{{ issue.description }}</h5>
        <p class="card-text">{{ issue.assignee }}</p>
        <h6 class="card-subtitle mb-2 text-body-secondary">{{ issue.reporter }}</h6>
        <small>{{ issue.created_on }}</small>
        <a href="{% url 'detail' issue.id %}">View Detail</a>
        <a href="{% url 'edit' issue.id %}" class="btn btn-primary">
            Edit...
            </a>
            <a href="{% url 'delete' issue.id %}" class="btn btn-danger">
            Delete...
            </a>
        
    </div>
</div>
<br />


</div>
{% endblock content %}

templates/issues/edit.html
{% extends 'base.html' %}

{% block title %}Edit Post{% endblock title %}

{% block content %}
<h1>Edit Post</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="Edit">
</form>
{% endblock content %}

templates/issues/list.html
{% extends 'base.html' %}

{% block title %}Issues{% endblock title %}

{% block content %}

<h1>Issues</h1>
<div class="container">

{% for issue in issue_list %}
<div class="card">
    <div class="card-body">
        <h4 class="card-title">{{ issue.summary }}</h4>
        <h5 class="card-subtitle mb-2 text-body-secondary">{{ issue.description }}</h5>
        <p class="card-text">{{ issue.assignee }}</p>
        <h6 class="card-subtitle mb-2 text-body-secondary">{{ issue.reporter }}</h6>
        <small>{{ issue.created_on }}</small>
        <a href="{% url 'detail' issue.id %}">View Detail</a>
        <a href="{% url 'edit' issue.id %}" class="btn btn-primary">
            Edit...
            </a>
            <a href="{% url 'delete' issue.id %}" class="btn btn-danger">
            Delete...
            </a>
        
    </div>
</div>
<br />

{% endfor %}
</div>
{% endblock content %}

templates/issues/new.html
{% extends 'base.html' %}

{% block title %}New{% endblock title %}

{% block content %}
<h1>New</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="Create">
</form>
{% endblock content %}

templates/pages/about.html
{% extends 'base.html' %}


{% block title %}About Us{% endblock title %}

{% block content %}

<h1>About Us</h1>
<p>Come checkout our Issues.</p>

{% endblock content %}

templates/pages/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}

<h1>Home</h1>
<p>Welcome To Our Issues!</p>

{% endblock content %}

templates/password_reset_email.html
{% load i18n %}{% autoescape off %}
You're receiving this email because you requested password reset instructions for your user account at {{ site_name }}.

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you have forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

The {{ site_name }}

{% endautoescape %}